title: BreakerBlog
iconURL: assets/default-icon.png
theme: jekyll-theme-time-machine

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: BreakerBox

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 2780321144
google_analytics: G-YGW88DM8EK
